In [1]:
# Add the Pandas dependency.
import pandas as pd

In [10]:
vine_data_to_load = "vine_table.csv"
vine_data_df = pd.read_csv(vine_data_to_load)
vine_data_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,R33UPQQUZQEM8,5.0,3.0,3.0,N,Y
1,R3IKTNQQPD9662,5.0,0.0,0.0,N,Y
2,R3U27V5QMCP27T,5.0,1.0,1.0,N,Y
3,R2TOH2QKNK4IOC,5.0,0.0,1.0,N,Y
4,R2XQG5NJ59UFMY,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
5069135,R1XMQ1X6POEZRD,5.0,1.0,1.0,N,N
5069136,R3MJ4ED61QJVQO,5.0,1.0,1.0,N,N
5069137,R3UIB7DM8VZSR8,3.0,0.0,0.0,N,N
5069138,R2YTBM6RDVNS4F,5.0,0.0,0.0,N,N
5069139,R5GBJG2FG9B6U,5.0,5.0,5.0,N,N

In [12]:
filtered_vine_df = vine_data_df[vine_data_df['total_votes']>=20]
filtered_vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
273,R31EUR60FV3BU5,4.0,32.0,39.0,N,N
413,R12Q1NO1HI9PP4,1.0,4.0,86.0,N,N
443,R3MDX24QDAT0OW,4.0,35.0,37.0,N,N
545,R2YVFZB4ESDT7D,5.0,139.0,141.0,N,Y
563,R6TNONSNFM82I,1.0,0.0,28.0,N,Y
...,...,...,...,...,...,...
5069065,R2KJ3U2FUMVUEA,2.0,36.0,42.0,N,N
5069072,R2EPRX3Y4R54ET,4.0,19.0,22.0,N,N
5069086,R18X24PLDWZK2Q,2.0,0.0,21.0,N,N
5069110,R3KYIA96PD8P8V,5.0,34.0,34.0,N,N
5069120,RUHPCLZVJPEDT,5.0,19.0,20.0,N,N

In [13]:
# retrieve all the rows where the number of helpful_votes divided by total_votes is equal to or greater than 50%.
helpful_vine_df = filtered_vine_df[(filtered_vine_df['helpful_votes'])/(filtered_vine_df['total_votes'])>=.5]
helpful_vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
273,R31EUR60FV3BU5,4.0,32.0,39.0,N,N
443,R3MDX24QDAT0OW,4.0,35.0,37.0,N,N
545,R2YVFZB4ESDT7D,5.0,139.0,141.0,N,Y
626,R2R8EWH1JUZCSI,5.0,16.0,21.0,N,N
980,R3I8GORXGEJL3R,4.0,95.0,103.0,N,Y
...,...,...,...,...,...,...
5069059,RZ1EBQF25E0IU,3.0,16.0,20.0,N,N
5069065,R2KJ3U2FUMVUEA,2.0,36.0,42.0,N,N
5069072,R2EPRX3Y4R54ET,4.0,19.0,22.0,N,N
5069110,R3KYIA96PD8P8V,5.0,34.0,34.0,N,N
5069120,RUHPCLZVJPEDT,5.0,19.0,20.0,N,N

In [14]:
# retrieves all the rows where a review was written as part of the Vine program (paid), vine == 'Y'
paid_vine_df = helpful_vine_df[helpful_vine_df['vine']=='Y']
paid_vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
1599848,R3PBQ665MBL8CP,3.0,66.0,72.0,Y,N
1651975,R3EMD30K7MNOZ0,2.0,20.0,25.0,Y,N
1688995,R2GF3ZLO2B0Y71,5.0,236.0,243.0,Y,N
1729649,R1F8T2Z7U3N6HL,3.0,11.0,20.0,Y,N
1871244,R5QTOT1GVR8RG,4.0,16.0,20.0,Y,N
2603239,R1KAQEESF0NUGV,4.0,27.0,29.0,Y,N
2845546,R1621B9AMVWI25,2.0,27.0,29.0,Y,N
2860248,R3FVGQVNBAZL8E,3.0,37.0,44.0,Y,N
2999810,R26ATTA765WHVX,5.0,21.0,23.0,Y,N
3006562,RMZYPFKES1ZK7,4.0,29.0,33.0,Y,N
3109236,R14DF0WKENBB1W,4.0,18.0,21.0,Y,N
3123561,RP8XXEUSRVK9W,3.0,18.0,22.0,Y,N
3147978,R385PHNA6E3GNZ,5.0,32.0,43.0,Y,Y
3150360,R3EF1FW33JGPV0,1.0,24.0,30.0,Y,N
3262191,R1QFLL874C1LYW,1.0,15.0,27.0,Y,N
3306433,R3K1A9MD4PVRH4,2.0,26.0,37.0,Y,N
3308821,RL6DMOWQJ56DX,3.0,19.0,27.0,Y,N
3515273,R2WDJTCP0CO4OF,4.0,26.0,28.0,Y,N
3553192,R9XFFVNYHTDOC,3.0,355.0,404.0,Y,N
3582755,R1ZMSEURPMYSEB,4.0,18.0,20.0,Y,N
3660793,RULANV8XV91MR,4.0,25.0,30.0,Y,N
3662363,R2YT7QUIR9VQ49,4.0,35.0,38.0,Y,N
3749813,R9PY1FWPZ7CFJ,2.0,13.0,22.0,Y,N
3754392,R1USEDY701F6U3,5.0,25.0,29.0,Y,N
3755955,R5OFZJT150RJT,4.0,33.0,34.0,Y,N
3794828,R2Y8EYZCTO7W1X,3.0,11.0,22.0,Y,N
3805448,RBP6QVHO4VCMK,3.0,142.0,150.0,Y,N
3814508,R37XEPS03X8N2W,5.0,117.0,130.0,Y,N
3822519,R2B6WYU4EDQSJ8,3.0,140.0,157.0,Y,N
3823442,R2SCJS7SBNV5PX,4.0,59.0,63.0,Y,N
3829318,R2F1RMTIO8HLSR,3.0,33.0,36.0,Y,N
3831111,R32RKGUEBLRD9E,4.0,20.0,22.0,Y,N
3832984,RKIK16SGTQUL9,3.0,34.0,38.0,Y,N
3849130,R33ZONGA340A5U,4.0,22.0,24.0,Y,N
3898424,R3LQ9OZW5B7ES6,3.0,21.0,21.0,Y,N
3911513,R35NYOJA1GJFM4,2.0,22.0,22.0,Y,N
3918201,R160Z7M8HOM75I,2.0,13.0,20.0,Y,N
3919580,R21VQYPFZXUQVX,3.0,44.0,45.0,Y,N
3922618,RS1GI9CTR1XRP,4.0,24.0,27.0,Y,N
3926843,R3BPJSL285RLPR,3.0,23.0,25.0,Y,N
3935986,R34IM90QYWA9Q,1.0,15.0,22.0,Y,Y
3937068,R1OAWE7H07QMIY,3.0,22.0,25.0,Y,N
3960886,R2OTCBWWUDNG0N,3.0,32.0,37.0,Y,N
4026811,RLZTRKNO8IAU8,5.0,54.0,56.0,Y,N
4046712,RMVYOZWLCN7DX,3.0,32.0,34.0,Y,N
4047387,R1US77YFAQ21JT,5.0,121.0,126.0,Y,N
4048104,R2NRHL9B4I43N5,4.0,18.0,22.0,Y,N
4050592,R1N4LM87NY6A8F,5.0,520.0,537.0,Y,N
4051814,R2ZIZDUL9E0QMN,5.0,18.0,20.0,Y,N

In [27]:
# retrieve all the rows where the review was not part of the Vine program (unpaid), vine == 'N'.

unpaid_vine_df = helpful_vine_df[helpful_vine_df['vine']=='N']
unpaid_vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
273,R31EUR60FV3BU5,4.0,32.0,39.0,N,N
443,R3MDX24QDAT0OW,4.0,35.0,37.0,N,N
545,R2YVFZB4ESDT7D,5.0,139.0,141.0,N,Y
626,R2R8EWH1JUZCSI,5.0,16.0,21.0,N,N
980,R3I8GORXGEJL3R,4.0,95.0,103.0,N,Y
...,...,...,...,...,...,...
5069059,RZ1EBQF25E0IU,3.0,16.0,20.0,N,N
5069065,R2KJ3U2FUMVUEA,2.0,36.0,42.0,N,N
5069072,R2EPRX3Y4R54ET,4.0,19.0,22.0,N,N
5069110,R3KYIA96PD8P8V,5.0,34.0,34.0,N,N
5069120,RUHPCLZVJPEDT,5.0,19.0,20.0,N,N

# Determine the total number of reviews, the number of 5-star reviews, and the percentage of 5-star reviews for the two types of review (paid vs unpaid).

In [23]:
paid_vine_reviews = paid_vine_df['review_id'].count()
paid_vine_reviews

49

In [25]:
paid_vine_reviews_5star = paid_vine_df[paid_vine_df['star_rating'] == 5]['star_rating'].count()
paid_vine_reviews_5star

9

In [42]:
paid_5star_percentage = paid_vine_reviews_5star/paid_vine_reviews*100
paid_5star_percentage

18.367346938775512

In [44]:
print(f'{paid_5star_percentage:2f}% of paid reviews are 5 star')

18.367347% of paid reviews are 5 star

In [28]:
unpaid_vine_reviews = unpaid_vine_df['review_id'].count()
unpaid_vine_reviews

151400

In [30]:
unpaid_vine_reviews_5star = unpaid_vine_df[unpaid_vine_df['star_rating'] == 5]['star_rating'].count()
unpaid_vine_reviews_5star

78061

In [45]:
unpaid_5star_percentage = unpaid_vine_reviews_5star/unpaid_vine_reviews*100
unpaid_5star_percentage

51.55944517833554

In [46]:
print(f'{unpaid_5star_percentage:2f}% of unpaid reviews are 5 star')

51.559445% of unpaid reviews are 5 star